### ISSUE TITLE
Add `filterMap`

### ISSUE THREAD

**Issue by peacememories** [pzp1997/assoc-list#3]
`filterMap` is a very useful tool for filtering collections.
Please consider adding this function.
I would be willing to submit a PR adding the function if that is fine with the maintainers :)

**Comment by pzp1997** [comment]
I am open to adding a `filterMap` function if you can give an example of how it would useful. Also could you please clarify the type and behavior of the function? I can think of several possible functions that might be named `filterMap` 🙂.

**Comment by peacememories** [comment]
`filterMap` generally does two things. It maps values to `Maybe`s according to a function, and then discards the `Nothings`
The signature is this:
```
flatMap : (key -> value -> Maybe newValue) -> Dict key value -> Dict key newValue
```

The usecase is filtering datastructures containing sum-types. In my specific case, I have a dictionary of "needs", that can either be `Persona` or `Other`, and I want to build a selector function `getPersonas : State -> Dict Url Persona`. Without `filterMap` this means writing a folding or recursive function, with filtermap it's just
```
getPersonas state =
    filterMap (\_ need -> case need of
        Persona p -> Just p
        _ -> Nothing
       )
    state.needs
```

The core `List` [implements this](https://package.elm-lang.org/packages/elm/core/1.0.2/List#filterMap), though not the core `Dict` (it's in [`dict-extra`](https://package.elm-lang.org/packages/elm-community/dict-extra/2.4.0/Dict-Extra#filterMap)), so maybe I'll create an `AssocList.Extra` module.

**Comment by pzp1997** [comment]
Okay, that seems reasonable to me. I have it slated for the next release.

**Comment by pzp1997** [comment]
Closing this issue since there is now [assoc-list-extra](https://package.elm-lang.org/packages/skyqrose/assoc-list-extra/latest/AssocList-Extra#filterMap) which has a `filterMap` function.
